[theme]
base="light"
primaryColor="#f39c12"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f5f6fa"
textColor="#2c3e50"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[ui]
favicon = "assets/logo.png"
